 
country_code_table = [
    [1, "AD"],
    [2, "AE"],
    [3, "AF"],
    [4, "AG"],
    [5, "AI"],
    [6, "AL"],
    [7, "AM"],
    [8, "AO"],
    [9, "AQ"],
    [10, "AR"],
    [11, "AS"],
    [12, "AT"],
    [13, "AU"],
    [14, "AW"],
    [15, "AX"],
    [16, "AZ"],
    [17, "BA"],
    [18, "BB"],
    [19, "BD"],
    [20, "BE"],
    [21, "BF"],
    [22, "BG"],
    [23, "BH"],
    [24, "BI"],
    [25, "BJ"],
    [26, "BL"],
    [27, "BM"],
    [28, "BN"],
    [29, "BO"],
    [30, "BQ"],
    [31, "BR"],
    [32, "BS"],
    [33, "BT"],
    [34, "BV"],
    [35, "BW"],
    [36, "BY"],
    [37, "BZ"],
    [38, "CA"],
    [39, "CC"],
    [40, "CD"],
    [41, "CF"],
    [42, "CG"],
    [43, "CH"],
    [44, "CI"],
    [45, "CK"],
    [46, "CL"],
    [47, "CM"],
    [48, "CN"],
    [49, "CO"],
    [50, "CR"],
    [51, "CU"],
    [52, "CV"],
    [53, "CW"],
    [54, "CX"],
    [55, "CY"],
    [56, "CZ"],
    [57, "DE"],
    [58, "DJ"],
    [59, "DK"],
    [60, "DM"],
    [61, "DO"],
    [62, "DZ"],
    [63, "EC"],
    [64, "EE"],
    [65, "EG"],
    [66, "EH"],
    [67, "ER"],
    [68, "ES"],
    [69, "ET"],
    [70, "FI"],
    [71, "FJ"],
    [72, "FK"],
    [73, "FM"],
    [74, "FO"],
    [75, "FR"],
    [76, "GA"],
    [77, "GD"],
    [78, "GE"],
    [79, "GF"],
    [80, "GG"],
    [81, "GH"],
    [82, "GI"],
    [83, "GL"],
    [84, "GM"],
    [85, "GN"],
    [86, "GP"],
    [87, "GQ"],
    [88, "GR"],
    [89, "GS"],
    [90, "GT"],
    [91, "GU"],
    [92, "GW"],
    [93, "GY"],
    [94, "HK"],
    [95, "HM"],
    [96, "HN"],
    [97, "HR"],
    [98, "HT"],
    [99, "HU"],
    [100, "ID"],
    [101, "IE"],
    [102, "IL"],
    [103, "IM"],
    [104, "IN"],
    [105, "IO"],
    [106, "IQ"],
    [107, "IR"],
    [108, "IS"],
    [109, "IT"],
    [110, "JE"],
    [111, "JM"],
    [112, "JO"],
    [113, "JP"],
    [114, "KE"],
    [115, "KG"],
    [116, "KH"],
    [117, "KI"],
    [118, "KM"],
    [119, "KN"],
    [120, "KP"],
    [121, "KR"],
    [122, "KW"],
    [123, "KY"],
    [124, "KZ"],
    [125, "LA"],
    [126, "LB"],
    [127, "LC"],
    [128, "LI"],
    [129, "LK"],
    [130, "LR"],
    [131, "LS"],
    [132, "LT"],
    [133, "LU"],
    [134, "LV"],
    [135, "LY"],
    [136, "MA"],
    [137, "MC"],
    [138, "MD"],
    [139, "ME"],
    [140, "MF"],
    [141, "MG"],
    [142, "MH"],
    [143, "MK"],
    [144, "ML"],
    [145, "MM"],
    [146, "MN"],
    [147, "MO"],
    [148, "MP"],
    [149, "MQ"],
    [150, "MR"],
    [151, "MS"],
    [152, "MT"],
    [153, "MU"],
    [154, "MV"],
    [155, "MW"],
    [156, "MX"],
    [157, "MY"],
    [158, "MZ"],
    [159, "NA"],
    [160, "NC"],
    [161, "NE"],
    [162, "NF"],
    [163, "NG"],
    [164, "NI"],
    [165, "NL"],
    [166, "NO"],
    [167, "NP"],
    [168, "NR"],
    [169, "NU"],
    [170, "NZ"],
    [171, "OM"],
    [172, "PA"],
    [173, "PE"],
    [174, "PF"],
    [175, "PG"],
    [176, "PH"],
    [177, "PK"],
    [178, "PL"],
    [179, "PM"],
    [180, "PN"],
    [181, "PR"],
    [182, "PS"],
    [183, "PT"],
    [184, "PW"],
    [185, "PY"],
    [186, "QA"],
    [187, "RE"],
    [188, "RO"],
    [189, "RS"],
    [190, "RU"],
    [191, "RW"],
    [192, "SA"],
    [193, "SB"],
    [194, "SC"],
    [195, "SD"],
    [196, "SE"],
    [197, "SG"],
    [198, "SH"],
    [199, "SI"],
    [200, "SJ"],
    [201, "SK"],
    [202, "SL"],
    [203, "SM"],
    [204, "SN"],
    [205, "SO"],
    [206, "SR"],
    [207, "SS"],
    [208, "ST"],
    [209, "SV"],
    [210, "SX"],
    [211, "SY"],
    [212, "SZ"],
    [213, "TC"],
    [214, "TD"],
    [215, "TF"],
    [216, "TG"],
    [217, "TH"],
    [218, "TJ"],
    [219, "TK"],
    [220, "TL"],
    [221, "TM"],
    [222, "TN"],
    [223, "TO"],
    [224, "TR"],
    [225, "TT"],
    [226, "TV"],
    [227, "TW"],
    [228, "TZ"],
    [229, "UA"],
    [230, "UG"],
    [231, "GB"],
    [232, "UM"],
    [233, "US"],
    [234, "UY"],
    [235, "UZ"],
    [236, "VA"],
    [237, "VC"],
    [238, "VE"],
    [239, "VG"],
    [240, "VI"],
    [241, "VN"],
    [242, "VU"],
    [243, "WF"],
    [244, "WS"],
    [245, "YE"],
    [246, "YT"],
    [247, "ZA"],
    [248, "ZM"],
    [249, "ZW"],
]

# The mapping from country to region is from the ICANN page
# https://meetings.icann.org/en/regions
#

cc_to_region = {
    "AC": "EUR",
    "AD": "EUR",
    "AE": "AP",
    "AF": "AP",
    "AG": "LAC",
    "AI": "EUR",
    "AL": "EUR",
    "AM": "AP",
    "AO": "AF",
    "AQ": "AP",
    "AR": "LAC",
    "AS": "NAM",
    "AT": "EUR",
    "AU": "AP",
    "AW": "EUR",
    "AX": "EUR",
    "AZ": "AP",
    "BA": "EUR",
    "BB": "LAC",
    "BD": "AP",
    "BE": "EUR",
    "BF": "AF",
    "BG": "EUR",
    "BH": "AP",
    "BI": "AF",
    "BJ": "AF",
    "BL": "LAC",
    "BM": "EUR",
    "BN": "AP",
    "BO": "LAC",
    "BQ": "LAC",
    "BR": "LAC",
    "BS": "LAC",
    "BT": "AP",
    "BV": "EUR",
    "BW": "AF",
    "BY": "EUR",
    "BZ": "LAC",
    "CA": "NAM",
    "CC": "AP",
    "CD": "AF",
    "CF": "AF",
    "CG": "AF",
    "CH": "EUR",
    "CI": "AF",
    "CK": "AP",
    "CL": "LAC",
    "CM": "AF",
    "CN": "AP",
    "CO": "LAC",
    "CR": "LAC",
    "CU": "LAC",
    "CV": "AF",
    "CW": "EUR",
    "CX": "AP",
    "CY": "AP",
    "CZ": "EUR",
    "DE": "EUR",
    "DJ": "AF",
    "DK": "EUR",
    "DM": "LAC",
    "DO": "LAC",
    "DZ": "AF",
    "EC": "LAC",
    "EE": "EUR",
    "EG": "AF",
    "EH": "AF",
    "ER": "AF",
    "ES": "EUR",
    "ET": "AF",
    "FI": "EUR",
    "FJ": "AP",
    "FK": "EUR",
    "FM": "AP",
    "FO": "EUR",
    "FR": "EUR",
    "GA": "AF",
    "GB": "EUR",
    "GD": "LAC",
    "GE": "AP",
    "GF": "EUR",
    "GG": "EUR",
    "GH": "AF",
    "GI": "EUR",
    "GL": "EUR",
    "GM": "AF",
    "GN": "AF",
    "GP": "EUR",
    "GQ": "AF",
    "GR": "EUR",
    "GS": "EUR",
    "GT": "LAC",
    "GU": "NAM",
    "GW": "AF",
    "GY": "LAC",
    "HK": "AP",
    "HM": "AP",
    "HN": "LAC",
    "HR": "EUR",
    "HT": "LAC",
    "HU": "EUR",
    "ID": "AP",
    "IE": "EUR",
    "IL": "AP",
    "IM": "EUR",
    "IN": "AP",
    "IO": "EUR",
    "IQ": "AP",
    "IR": "AP",
    "IS": "EUR",
    "IT": "EUR",
    "JE": "EUR",
    "JM": "LAC",
    "JO": "AP",
    "JP": "AP",
    "KE": "AF",
    "KG": "AP",
    "KH": "AP",
    "KI": "AP",
    "KM": "AF",
    "KN": "LAC",
    "KP": "AP",
    "KR": "AP",
    "KW": "AP",
    "KY": "EUR",
    "KZ": "AP",
    "LA": "AP",
    "LB": "AP",
    "LC": "LAC",
    "LI": "EUR",
    "LK": "AP",
    "LR": "AF",
    "LS": "AF",
    "LT": "EUR",
    "LU": "EUR",
    "LV": "EUR",
    "LY": "AF",
    "MA": "AF",
    "MC": "EUR",
    "MD": "EUR",
    "ME": "EUR",
    "MF": "LAC",
    "MG": "AF",
    "MH": "AP",
    "MK": "EUR",
    "ML": "AF",
    "MM": "AP",
    "MN": "AP",
    "MO": "AP",
    "MP": "NAM",
    "MQ": "EUR",
    "MR": "AF",
    "MS": "EUR",
    "MT": "EUR",
    "MU": "AF",
    "MV": "AP",
    "MW": "AF",
    "MX": "LAC",
    "MY": "AP",
    "MZ": "AF",
    "NA": "AF",
    "NC": "EUR",
    "NE": "AF",
    "NF": "AP",
    "NG": "AF",
    "NI": "LAC",
    "NL": "EUR",
    "NO": "EUR",
    "NP": "AP",
    "NR": "AP",
    "NU": "AP",
    "NZ": "AP",
    "OM": "AP",
    "PA": "LAC",
    "PE": "LAC",
    "PF": "EUR",
    "PG": "AP",
    "PH": "AP",
    "PK": "AP",
    "PL": "EUR",
    "PM": "EUR",
    "PN": "EUR",
    "PR": "NAM",
    "PS": "AP",
    "PT": "EUR",
    "PW": "AP",
    "PY": "LAC",
    "QA": "AP",
    "RE": "EUR",
    "RO": "EUR",
    "RS": "EUR",
    "RU": "EUR",
    "RW": "AF",
    "SA": "AP",
    "SB": "AP",
    "SC": "AF",
    "SD": "AF",
    "SE": "EUR",
    "SG": "AP",
    "SH": "EUR",
    "SI": "EUR",
    "SJ": "EUR",
    "SK": "EUR",
    "SL": "AF",
    "SM": "EUR",
    "SN": "AF",
    "SO": "AF",
    "SR": "LAC",
    "SS": "AF",
    "ST": "AF",
    "SV": "LAC",
    "SX": "LAC",
    "SY": "AP",
    "SZ": "AF",
    "TC": "EUR",
    "TD": "AF",
    "TF": "EUR",
    "TG": "AF",
    "TH": "AP",
    "TJ": "AP",
    "TK": "AP",
    "TL": "AP",
    "TM": "AP",
    "TN": "AF",
    "TO": "AP",
    "TR": "AP",
    "TT": "LAC",
    "TV": "AP",
    "TW": "AP",
    "TZ": "AF",
    "UA": "EUR",
    "UG": "AF",
    "UK": "EUR",
    "UM": "NAM",
    "US": "NAM",
    "UY": "LAC",
    "UZ": "AP",
    "VA": "EUR",
    "VC": "LAC",
    "VE": "LAC",
    "VG": "EUR",
    "VI": "NAM",
    "VN": "AP",
    "VU": "AP",
    "WF": "EUR",
    "WS": "AP",
    "YE": "AP",
    "YT": "EUR",
    "ZA": "AF",
    "ZM": "AF",
    "ZW": "AF"
}

country_name = {
    "AC": "Ascension Island",
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Aland Islands",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint Barthelemy",
    "BM": "Bermuda",
    "BN": "Brunei Darussalam",
    "BO": "Plurinational State of Bolivia",
    "BQ": "Bonaire, Sint Eustatius and Saba",
    "BR": "Brazil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    "BV": "Bouvet Island",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CD": "The Democratic Republic of the Congo",
    "CF": "Central African Republic",
    "CG": "Republic of Congo",
    "CH": "Switzerland",
    "CI": "Cote d'Ivoire",
    "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CW": "Curacao",
    "CX": "Christmas Island",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "The Commonwealth of Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "EH": "Western Sahara",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Islands (Malvinas)",
    "FM": "Federated States of Micronesia",
    "FO": "Faroe Islands",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom of Great Britain and Northern Ireland",
    "GD": "Grenada",
    "GE": "Georgia",
    "GF": "French Guiana",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "Republic of Gambia",
    "GN": "Republic of Guinea",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GS": "South Georgia and the South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HK": "Hong Kong, China",
    "HM": "Heard Island and McDonald Islands",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IM": "Isle of Man",
    "IN": "India",
    "IO": "British Indian Ocean Territory",
    "IQ": "Iraq",
    "IR": "Islamic Republic of Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyz Republic",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comoros",
    "KN": "Saint Kitts and Nevis",
    "KP": "Democratic People's Republic of Korea",
    "KR": "Republic of Korea",
    "KW": "Kuwait",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",
    "LA": "Lao People's Democratic Republic",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Republic of Moldova",
    "ME": "Montenegro",
    "MF": "Saint Martin (French part)",
    "MG": "Madagascar",
    "MH": "Republic of the Marshall Islands",
    "MK": "North Macedonia",
    "ML": "Mali",
    "MM": "Republic of the Union of Myanmar",
    "MN": "Mongolia",
    "MO": "Macao, China",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Republic of Panama",
    "PE": "Peru",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "Saint Pierre and Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PS": "Palestine",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SH": "Saint Helena, Ascension and Tristan da Cunha",
    "SI": "Slovenia",
    "SJ": "Svalbard and Jan Mayen",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Republic of Suriname",
    "SS": "South Sudan",
    "ST": "Sao Tome and Principe",
    "SV": "El Salvador",
    "SX": "Sint Maarten (Dutch part)",
    "SY": "Syrian Arab Republic",
    "SZ": "Eswatini",
    "TC": "Turks and Caicos Islands",
    "TD": "Republic of Chad",
    "TF": "French Southern Territories",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TK": "Tokelau",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TR": "Republic of Turkiye",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Chinese Taipei",
    "TZ": "United Republic of Tanzania",
    "UA": "Ukraine",
    "UG": "Uganda",
    "UK": "United Kingdom of Great Britain and Northern Ireland",
    "UM": "United States Minor Outlying Islands",
    "US": "United States of America",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VA": "Holy See (Vatican City State)",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Bolivarian Republic of Venezuela",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "VN": "Viet Nam",
    "VU": "Vanuatu",
    "WF": "Wallis And Futuna",
    "WS": "Samoa",
    "YE": "Yemen",
    "YT": "Mayotte",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}

def country_code_from_number(number):
    alpha_code = "ZZ"
    if number > 0 and number <= 249:
        table_line = country_code_table[number - 1]
        alpha_code= table_line[1]
    return alpha_code

def country_code_from_c999(c999):
    alpha_code = 'ZZ'
    if c999.startswith("c"):
        try:
            number = int(c999[1:])
            if number > 0 and number <= 249:
                table_line = country_code_table[number - 1]
                alpha_code = table_line[1]
        except:
            pass
    return alpha_code


