Document: ithitools
Title: Debian ithitools Manual
Author: <insert document author here>
Abstract: This manual describes what ithitools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ithitools/ithitools.sgml.gz

Format: postscript
Files: /usr/share/doc/ithitools/ithitools.ps.gz

Format: text
Files: /usr/share/doc/ithitools/ithitools.text.gz

Format: HTML
Index: /usr/share/doc/ithitools/html/index.html
Files: /usr/share/doc/ithitools/html/*.html
